name: PRODUCTION Release

on:
  workflow_dispatch:
    inputs:
      service_deploy:
        description: 'Services to deploy'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - app
          - lambda
          - cdk

jobs:
  build-and-push-app:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
    with:
      aws_environment: prod
    if: github.event.inputs.service_deploy == 'all' || github.event.inputs.service_deploy == 'app'

  build-and-push-lambdas:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
    with:
      aws_environment: prod
    if: github.event.inputs.service_deploy == 'all' || github.event.inputs.service_deploy == 'lambda'

  deploy-cdk:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
    with:
      aws_environment: prod
    needs: 
      - build-and-push-app
      - build-and-push-lambdas
    if: github.event.inputs.service_deploy == 'all' || github.event.inputs.service_deploy == 'cdk'
